name: 'risk_pipeline'
version: '1.0.0'
config-version: 2

profile: 'risk_pipeline'

model-paths: ["models"]
test-paths: ["tests"]

models:
  risk_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
